[source]
type = "baserow"

[[filter]]
field = "Case Status"
valid_keys = ["Solved", "Unsolved", "VUS"]

[[filter]]
field = "Datenverarbeitung"
valid_keys = [true,]

[baserow]
root_table_id = 579
link_table_mappings = [
  ["Clinician", 582],
  ["Findings", 581],
]
